"""Provider-neutral integration boundaries."""

from leakproof.providers.contracts import (
    CaseInsightProvider,
    CaseInsightRequest,
    CaseInsightResult,
    CohortAnalysisProvider,
    CohortAnalysisRequest,
    CohortAnalysisResult,
    CreateInvoiceRequest,
    CreateOrderRequest,
    CreateSubscriptionRequest,
    EmailProvider,
    EmailSendRequest,
    EmailSendResult,
    Invoice,
    InvoiceProvider,
    Payment,
    PaymentOrder,
    PaymentProvider,
    ProviderError,
    Subscription,
    SubscriptionProvider,
)
from leakproof.providers.openai import OpenAICaseInsightProvider, OpenAICohortAnalysisProvider
from leakproof.providers.razorpay import RazorpayPaymentProvider, RazorpayProvider
from leakproof.providers.resend import ResendEmailProvider

__all__ = [
    "CaseInsightProvider",
    "CaseInsightRequest",
    "CaseInsightResult",
    "CohortAnalysisProvider",
    "CohortAnalysisRequest",
    "CohortAnalysisResult",
    "CreateInvoiceRequest",
    "CreateOrderRequest",
    "CreateSubscriptionRequest",
    "EmailProvider",
    "Invoice",
    "InvoiceProvider",
    "EmailSendRequest",
    "EmailSendResult",
    "Payment",
    "PaymentOrder",
    "PaymentProvider",
    "ProviderError",
    "Subscription",
    "SubscriptionProvider",
    "RazorpayProvider",
    "RazorpayPaymentProvider",
    "OpenAICaseInsightProvider",
    "OpenAICohortAnalysisProvider",
    "ResendEmailProvider",
]
