from enum import StrEnum


class DataProvenance(StrEnum):
    LIVE_PROVIDER_VERIFIED = "LIVE_PROVIDER_VERIFIED"
    SIMULATED_END_TO_END = "SIMULATED_END_TO_END"
    ARCHITECTURE_READY = "ARCHITECTURE_READY"
